name: Building TWRP Android 12.1

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  watch:
    types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  DEVICE: cheeseburger
  DT_LINK: https://github.com/faoliveira78/android_device_oneplus_cheeseburger -b android-12.1
  DT_PATH: device/oneplus/cheeseburger
  KERNEL_LINK: https://github.com/xLexip/android_kernel_oneplus_msm8998 -b twelve
  KERNEL_PATH: kernel/oneplus/msm8998
  TARGET: recoveryimage
  CHAT_ID: ${{ secrets.TELEGRAM_TO }}
  BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TZ: America/Maceio

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

       - name: Checkout
         uses: actions/checkout@v3
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Initializing environment
         run: |
            git config --global user.name "Fernando Oliveira"
            git config --global user.email "fernandoaju78@gmail.com"
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -y -qq upgrade
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2 libncurses5 libncurses5-dev
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo

       - name: Set Swap Space
         uses: pierotofy/set-swap-space@master
         with:
           swap-size-gb: 12

       - name: Sync TWRP A12.1 source device tree and Kernel
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             source build/envsetup.sh
             repopick 5405 5540
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             git clone $KERNEL_LINK --depth=1 --single-branch $KERNEL_PATH

       - name: Building TWRP
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-eng
              rm -rf .repo/
              mka -j$(nproc --all) $TARGET

       - name: Uploading recovery image
         run: |
              cd work/out/target/product/$DEVICE
              curl -F chat_id=$CHAT_ID -F document=@recovery.img https://api.telegram.org/bot$BOT_TOKEN/sendDocument
              curl -F chat_id=$CHAT_ID -F document=@Image.gz-dtb https://api.telegram.org/bot$BOT_TOKEN/sendDocument
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet Image.gz-dtb
              ./transfer wet recovery.img
