name: Building TWRP Android 12.1

on:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  watch:
    types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  DEVICE: cheeseburger
  DT_LINK: https://github.com/faoliveira78/android_device_oneplus_cheeseburger -b android-13
  DT_PATH: device/oneplus/cheeseburger
  KERNEL_LINK: #https://github.com/faoliveira78/android_kernel_oneplus_msm8998 -b lineage-20
  KERNEL_PATH: #kernel/oneplus/msm8998
  TARGET: recoveryimage
  CHAT_ID: ${{ secrets.TELEGRAM_TO }}
  BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

       - name: Checkout
         uses: actions/checkout@v3
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Initializing environment
         run: |
            git config --global user.name "Fernando Oliveira"
            git config --global user.email "fernandoaju78@gmail.com"
            sudo apt-get update && sudo apt-get install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2 libncurses5 libncurses5-dev
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo

       - name: Set Swap Space
         uses: pierotofy/set-swap-space@master
         with:
           swap-size-gb: 12

       - name: Sync TWRP A12.1 source device tree and Kernel
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j$(nproc --all)
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
              
             if [ -n "$KERNEL_LINK" ]; then
              git clone $KERNEL_LINK --depth=1 --single-branch $KERNEL_PATH
             else
              echo "kernel link does not exist, skipping clone."
             fi
             
             if [[ "$MANIFEST" == *"faoliveira78"* ]]; then
              git -C bootable/recovery fetch https://gerrit.twrp.me/android_bootable_recovery refs/changes/89/6289/1 && git -C bootable/recovery cherry-pick FETCH_HEAD
              git -C bootable/recovery fetch https://gerrit.twrp.me/android_bootable_recovery refs/changes/63/6363/1 && git -C bootable/recovery cherry-pick FETCH_HEAD
             else
              source build/envsetup.sh
              repopick 6289 6363
             fi

       - name: Building TWRP
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-eng
              rm -rf .repo/
              mka -j$(nproc --all) $TARGET

       - name: Uploading recovery image
         run: |
              cd work/out/target/product/$DEVICE
              curl -F chat_id=$CHAT_ID -F document=@recovery.img https://api.telegram.org/bot$BOT_TOKEN/sendDocument >& /dev/null
              curl -F chat_id=$CHAT_ID -F document=@kernel https://api.telegram.org/bot$BOT_TOKEN/sendDocument >& /dev/null
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet kernel
              ./transfer wet recovery.img
